web:
    image: lampmageu
    links:
        - db
    ports:
        - "80:80"
db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: magento2
        MYSQL_USER: jason
        MYSQL_PASSWORD: test

