FROM php:5.6-apache
RUN apt-get update && apt-get -y install \
    libmcrypt-dev \
    libxslt-dev \
    libicu-dev \
    libpng-dev \
    zlib1g-dev  \
    libcurl4-openssl-dev \
    nano \
    vim \
    ack-grep \
    wget \
    git \
    openssh-client \
    telnet
RUN docker-php-ext-install \
    mbstring \
    mcrypt \
    xsl \
    intl \
    gd \
    curl \
    mysql \
    pdo_mysql \
    zip 
RUN curl -L https://pecl.php.net/get/xdebug-2.3.3.tgz >> /usr/src/php/ext/xdebug.tgz \
    && tar -xf /usr/src/php/ext/xdebug.tgz -C /usr/src/php/ext/ \
    && rm /usr/src/php/ext/xdebug.tgz \
    && docker-php-ext-install xdebug-2.3.3 \
COPY config/php.ini /usr/local/etc/php/ \
    && config/perm.sh /var/www/
    && code/ /var/www/html/
RUN chmod -R 777 /var/www/html/var/ \
    && chmod -R 777 /var/www/html/app/etc/ \
    && chmod -R 777 /var/www/html/pub/media
    && chmod -R 777 /var/www/html/pub/static
    && chmod +x /var/www/perm.sh
RUN /var/www/perm.sh /var/www/html/ && curl -sS https://getcomposer.org/installer | \
    php -- --install-dir=/usr/local/bin --filename=composer
