version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      front:
        ipv4_address: 172.22.0.2
networks:
  front:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16